# This workflow is triggered on a push event to any branch.
# This includes pushes that create new branches.
# It calls the reusable workflow to build and push the Docker image..

name: CI

on:
  # workflow_dispatch:
  push:

    #  branches: [ $default-branch ]

jobs:
  docker:
    # This job uses the reusable workflow defined in the other file.
    # The path must be relative to the root of the repository.
    uses: ./.github/workflows/reusable-docker-build-push.yml
    
    # Provide the required inputs for the reusable workflow.
    with:
      registry_hostname: registrytbd.azurecr.io
      image_name: posapi
      build_context: ./src
      dockerfile_path: Dockerfile
      registry_username: ${{ vars.ACR_USER }}
      
    # Pass the required secrets to the reusable workflow.
    # The key 'registry_password' must match the secret name in the 'workflow_call' trigger.
    secrets:
      registry_password: ${{ secrets.ACR_SECRET }}

